name: Lint Code
description: Lint the Python code via Ruff linting

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Ruff Check
      run: |
        python -m pip install ruff
        ruff check --output-format=github